# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-23 04:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=200)),
                ('url', models.CharField(default='/', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('info', models.CharField(max_length=50)),
                ('url', models.CharField(default='/', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('fps', models.IntegerField(default=25)),
                ('camera', models.CharField(default='MainCAM', max_length=50)),
                ('url', models.CharField(default='/', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('info', models.CharField(max_length=50)),
                ('url', models.CharField(default='/', max_length=200)),
                ('genus', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='main.Genus')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=50)),
                ('url', models.CharField(default='/', max_length=200)),
                ('genus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Genus')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Project')),
            ],
        ),
        migrations.AddField(
            model_name='entity',
            name='project',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='main.Project'),
        ),
        migrations.AddField(
            model_name='entity',
            name='tag',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='main.Tag'),
        ),
    ]
